### API HTTP request tests for orders

### Token for user admin (admin)
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkByZXN0YXVyYW50LmZpIiwicGhvbmUiOiIrMzU4MTIzNDU2Nzg5Iiwicm9sZSI6ImFkbWluIiwiaXNfYWN0aXZlIjoxLCJpYXQiOjE3NjQ2NjQzMDEsImV4cCI6MTc2NDgzNzEwMX0.-xJjn3Id7t_V6N13C0vb7-lfgOjn-_rNJOCN74DtP40

### Login as customer
@user2_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6ImxpaXNhIiwiZW1haWwiOiJsaWlzYUBleGFtcGxlLmZpIiwicGhvbmUiOiIrMzU4MTEyMjMzNDQ1Iiwicm9sZSI6ImN1c3RvbWVyIiwiaXNfYWN0aXZlIjoxLCJpYXQiOjE3NjQ2ODI0OTYsImV4cCI6MTc2NDg1NTI5Nn0.1boD-XXYaX2fD4rS2m926V6UnDyyg2m0g7Z0ZaueRCM



### Login as admin to get token
 POST http://localhost:3000/api/v1/auth/login
 Content-Type: application/json

 {
    "username": "admin",
    "password": "password"
 }

### Login as customer (liisa)
 POST http://localhost:3000/api/v1/auth/login
 Content-Type: application/json

 {
    "username": "liisa",
    "password": "password"
 }


### Orders

### Get all orders (admin only - require token)
GET http://localhost:3000/api/v1/orders
Authorization: Bearer {{adminToken}}


### Get user's orders by user ID (only order owner or admin)
GET http://localhost:3000/api/v1/orders/user/2
Authorization: Bearer {{user2_token}}


### Get order by ID
GET http://localhost:3000/api/v1/orders/3
Authorization: Bearer {{user2_token}}


### Get order details with items (only order owner or admin)
GET http://localhost:3000/api/v1/orders/1/details
Authorization: Bearer {{user2_token}}


### Create order as guest (No Token needed) - return full order details immediately
### (Note: Guest cannot view order later without account)
POST http://localhost:3000/api/v1/orders
Content-Type: application/json

{
    "user_id": null,
    "customer_name": "minna Meikäläinen",
    "customer_email": "minnaa@test.com",
    "customer_phone": "+358223344556",
    "order_type": "delivery",
    "delivery_address": "test 123, 001 Helsinki",
    "items": [
        {
            "menu_item_id": 3,
            "item_name": "Kanatacot x 3",
            "quantity": 2,
            "unit_price": 14.50,
            "selected_spice_level": 3,
            "special_requests": "Extra salsa"
        }
    ]
}


### Create new order (registered customer)
POST http://localhost:3000/api/v1/orders
Content-Type: application/json

{
    "user_id": 2,
    "customer_name": "Liisa Virtanen",
    "customer_email": "liisa@example.fi",
    "customer_phone": "+358112233445",
    "order_type": "delivery",
    "delivery_address": "test 123, 001 Helsinki",
    "items": [
        {
            "menu_item_id": 7,
            "item_name": "Burrito",
            "quantity": 1,
            "unit_price": 16.90,
            "selected_protein": "chicken",
            "selected_spice_level": 2,
            "special_requests": "No onions"
        },
        {
            "menu_item_id": 11,
            "item_name": "Jarritos Lime",
            "quantity": 2,
            "unit_price": 3.90
        }
    ]
}


### Update order (admin only)
PUT http://localhost:3000/api/v1/orders/5
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "customer_name": "Maija Lehtonen",
    "customer_email": "maija.lehtonen@example.com",
    "customer_phone": "+358992244444",
    "order_type": "pickup",
    "delivery_address": "Leppavaara 12, 0070 Espoo"
}


### Delete order (admin only)
DELETE http://localhost:3000/api/v1/orders/6
Authorization: Bearer {{adminToken}}



### Negative tests

### Try to access route without token (should fail with 401)
GET http://localhost:3000/api/v1/orders


### Try to access admin route with customer token (should fail with 403
GET http://localhost:3000/api/v1/orders
Authorization: Bearer {{user2_token}}



### Try to access another user's orders (should fail with 403)
GET http://localhost:3000/api/v1/orders/user/3
Authorization: Bearer {{user2_token}}


### Try to access another user's order by ID (Should fail with 403)
GET http://localhost:3000/api/v1/orders/2
Authorization: Bearer {{user2_token}}





### Validation tests

### Create order with missing required fields (should fail 400)
POST http://localhost:3000/api/v1/orders
Content-Type: application/json

{
    "customer_name": "Test User",
    "customer_email": "test@example.com"
    // Missing phone, order_type, items
}


### Create order with invalid email (should fail 400)
POST http://localhost:3000/api/v1/orders
Content-Type: application/json

{
    "customer_name": "Test User",
    "customer_email": "invalid-email",
    "customer_phone": "+358123456789",
    "order_type": "pickup",
    "items": [
        {
         "menu_item_id": 3,
            "item_name": "Kanatacot x 3",
            "quantity": 2,
            "unit_price": 14.50
        }
    ]
}

### Create order with empty items array (should fail 400)
POST http://localhost:3000/api/v1/orders
Content-Type: application/json

{
    "customer_name": "Test User",
    "customer_email": "test@example.com",
    "customer_phone": "+358123456789",
    "order_type": "pickup",
    "items": []
}
