### Allergens

### Get all allergens
GET http://localhost:3000/api/v1/allergens

### Get allergen by ID (Lactose-free)
GET http://localhost:3000/api/v1/allergens/1


### Get allergen by ID (Gluten-free)
GET http://localhost:3000/api/v1/allergens/2


### Get allergen by ID (Dairy-free)
GET http://localhost:3000/api/v1/allergens/3


### Get allergen by ID (Vegan)
GET http://localhost:3000/api/v1/allergens/4


### Get allergens for menu item
GET http://localhost:3000/api/v1/allergens/menu-item/8


