### API HTTP request tests for orders

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkByZXN0YXVyYW50LmZpIiwicGhvbmUiOiIrMzU4MTIzNDU2Nzg5Iiwicm9sZSI6ImFkbWluIiwiaXNfYWN0aXZlIjoxLCJpYXQiOjE3NjQ2NjQzMDEsImV4cCI6MTc2NDgzNzEwMX0.-xJjn3Id7t_V6N13C0vb7-lfgOjn-_rNJOCN74DtP40


### First login as admin to get token
 POST http://localhost:3000/api/v1/auth/login
 Content-Type: application/json

 {
    "username": "admin",
    "password": "password"
 }



### Orders

### Get all orders
GET http://localhost:3000/api/v1/orders
Authorization: Bearer {{token}}


### Get order by ID
GET http://localhost:3000/api/v1/orders/4


### Get order details with items
GET http://localhost:3000/api/v1/orders/1/details


### Get user's orders by user ID
GET http://localhost:3000/api/v1/orders/user/1


### Create new order (not registered customer)
POST http://localhost:3000/api/v1/orders
Content-Type: application/json

{
    "user_id": 3,
    "customer_name": "minna Meikäläinen",
    "customer_email": "minnaa@test.com",
    "customer_phone": "+358223344556",
    "order_type": "delivery",
    "delivery_address": "test 123, 001 Helsinki",
    "items": [
        {
            "menu_item_id": 3,
            "item_name": "Kanatacot x 3",
            "quantity": 2,
            "unit_price": 14.50,
            "selected_spice_level": 3,
            "special_requests": "Extra salsa"
        }
    ]
}


### Create new order (registered customer)
POST http://localhost:3000/api/v1/orders
Content-Type: application/json

{
    "user_id": 2,
    "customer_name": "Liisa Virtanen",
    "customer_email": "liisa@example.fi",
    "customer_phone": "+358112233445",
    "order_type": "delivery",
    "delivery_address": "test 123, 001 Helsinki",
    "items": [
        {
            "menu_item_id": 7,
            "item_name": "Burrito",
            "quantity": 1,
            "unit_price": 16.90,
            "selected_protein": "chicken",
            "selected_spice_level": 2,
            "special_requests": "No onions"
        },
        {
            "menu_item_id": 11,
            "item_name": "Jarritos Lime",
            "quantity": 2,
            "unit_price": 3.90
        }
    ]
}


### Update order
PUT http://localhost:3000/api/v1/orders/14
Content-Type: application/json

{
    "customer_name": "Liisa Hoffren",
    "customer_email": "liisa.hoffren@example.com",
    "customer_phone": "+358992233445",
    "order_type": "delivery",
    "delivery_address": "Karamalmi 12, 0070 Espoo"
}


### Delete order
DELETE http://localhost:3000/api/v1/orders/11
